### ISSUE TITLE
Path configuration issue

### ISSUE THREAD

**Issue by fpaparoni** [geonetwork/geonetwork-helm-charts#3]
I'm using the helm chart and I modified only the ingress part to be publish it on my server

```
ingress:
  enabled: true
  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt-http01-prod 
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
  hosts:
    - host: geonetwork.myhost.com
      paths:
        - "/datahub"
  tls: 
    - secretName: geonetwork-myhost-com-key-pair
      hosts:
        - geonetwork.myhost.com
  className: "external-nginx"
```

The application starts and it's available using https://geonetwork.myhost.com/datahub but in the homepage I receive an error

An error was received
Http failure response for https://geonetwork.myhost.com/geonetwork/srv/api/me: 404 Not Found

Is there some additional configuration in this chart that can be used to manage the relative path?
