### ISSUE TITLE
Datahub: conf path mismatch when using georchestra config datadir

### ISSUE THREAD

**Issue by jeanpommier** [geonetwork/geonetwork-helm-charts#7]
By default:

- the datahub pod looks for the config at `/etc/datahub/{{ .Values.configuration.override_directories.config_directory_override }}`, so `/etc/datahub/config` ( https://github.com/geonetwork/geonetwork-helm-charts/blame/main/datahub/templates/datahub-deployment.yaml#L58)
- but the georchestra datadir is mounted at /etc/datahub, which means that the conf will be at /etc/datahub/datahub/conf

So they do not match. 

I understand that datahub can be deployed independently of geOrchestra and that this only means changing a few values for the chart, but wouldn't it be great if it deployed out-of-the-box when used in a geOrchestra context ?

**Comment by edevosc2c** [comment]
That's why, in the context of georchestra, you should do like this:
```
configuration:
  # The directory name is the directory from the root of the git repository
  # If the datahub config is located in the /conf directory then write conf
  # in config_directory_override.
  override_directories:
    config_directory_override: "datahub/conf"
    assets_directory_override: "datahub/assets"
```

> but wouldn't it be great if it deployed out-of-the-box when used in a geOrchestra context ?

Sure but in this case that's why there is an open issue for tracking the work in implementing the datahub chart as a subchart in the helm chart of georchestra: https://github.com/georchestra/helm-georchestra/issues/34
